version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - 15672:15672
  
  chunk_manager:
    container_name: chunk_manager
    image: chunk_manager:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - SEND_QUEUE=chunks
    volumes:
      - ./chunk_manager/data:/data

  master_controller:
    container_name: master_controller
    image: master_controller:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=chunks
      - SEND_QUEUE=map_city
      - TOTAL_MAP_WORKERS=1

  map_worker1:  
    container_name: map_worker
    image: map_worker:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=1
    volumes:
      - ./map_worker/data:/data

  cities_resume1:  
    container_name: cities_resume
    image: cities_resume:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONSUMER_ID=1

  resume_master_controller:  
    container_name: resume_master_controller
    image: resume_master_controller:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=master_map
      - SEND_QUEUE=cities_resume

  resume_master_controller2:  
    container_name: resume_master_controller2
    image: resume_master_controller:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=resume_master
      - SEND_QUEUE=top_cities

  top_cities_controller:  
    container_name: top_cities_controller
    image: top_cities_controller:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  summary_controller:  
    container_name: summary_controller
    image: summary_controller:latest
    entrypoint: python3 /main.py
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - RECV_QUEUE=summary_resume
